# "PROTOCOL": redis protocol, "STRING": readable command & reply, "ROW" : row lines
message = "PROTOCOL"
# thread: ThWorker, rx: RxWorker, coroutine: CoroutineWorker
worker = "coroutine"

[receiver]
class = "ys.phoebos.redis.replay.receiver.KafkaReceiver"
polltimeout = 100    #ms

topic = "redis"
bootstrap-servers = "127.0.0.1:9092"
group-id = "redisremote"

[redis]
connip = "127.0.0.1"
connport = 6379
